# Generated by Django 2.1.5 on 2019-02-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='iid',
            field=models.IntegerField(default=0),
        ),
    ]
