# Generated by Django 2.1.5 on 2019-02-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_items_iid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='iid',
        ),
    ]
